"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages

APP = ['src/main.py']
# DATA_FILES = ["log", "archive"]
OPTIONS = {
    "iconfile": "include/img/app.icns",
    "emulate_shell_environment": 1,
    "packages": find_packages(),
}

setup(
    app=APP,
    version="2.3",
    name="PodcastTool",
    # data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
